import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Lexend } from "next/font/google";
import Provider from "./provider";
const lexend = Lexend({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider> 
    <html lang="en">
      <body
        className={ lexend.className }
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider> 
  );
}
